### ISSUE TITLE
munge has no logs

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/snap-slurm#79]
I'm trying to debug in relation to #78 

But I dont see any logs on either of my hosts.

root@n-c72:~# ls /var/snap/slurm/common/var/log/munge/

**Comment by egee-irl** [comment]
Logging is currently a little inconsistant with some services writing to stdout (into the journald) and other services writing to a log file.

Munged is a service that writes straight to stdout which means you can access the logs by interacting with the systemd journal like so: `journalctl -eu snap.slurm.munged.service`.

If the logs you are searching for are located there, I can add to the documentation that the munged logs are located in the journal rather than a config file.

**Comment by erik78se** [comment]
Is it possible to munged log to file since the log directory is still there. It's confusing to have it otherwise.
For consistency it would be good to have logs in like one place for all services embedded in the snap.

**Comment by egee-irl** [comment]
I spent some time on this and, believe it or not, Munged writing to a log file is a somewhat new feature and it is rather clunky. The most consistent behavior I've seen with Munged is to just let it log to stdout which is captured by the Snap logger.

That being said, all of Munged's logs can be seen by doing `snap logs slurm.munged`

**Comment by erik78se** [comment]
Getting the logs into a file is great if possible but mean while docs about
this is of course better than nothing.

Den lör 11 juli 2020 00:16Brian <notifications@github.com> skrev:

**Comment by jamesbeedy** [comment]
Closing this as munge now logs to a file.
